name: Pi Coding Agent
on:
  push:
    branches:
    - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  pi-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Pi Review
        uses: shaftoe/pi-coding-agent-action@v2
        if: contains(github.event.head_commit.message, '/pi')
        with:
          provider: 'google'
          model: 'gpt-4o'
          prompt: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
          token: ${{ secrets.COPILOT_AGENT_TOKEN }}