name: Pi Coding Agent
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  pi-agent:
    if: contains(github.event.comment.body, '/pi')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      #- name: Setup Node
      #  uses: actions/setup-node@v6
      #  with:
      #    node-version: 24

      #- name: Pi Review
      #  uses: shaftoe/pi-coding-agent-action@v2
      #  with:
      #    provider: 'gcloud'
      #    model: 'claude-opus-4-6'
      #    github_token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
      #    token: ${{ secrets.COPILOT_AGENT_TOKEN }}
      #    thinking_level: medium
      #    extensions:
      #      git:https://github.com/maxandersen/pi-vertex-anthropic

      - name: auth
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}'
        
      - name: Run Pi.dev Agent
        env:
          VERTEX_LOCATION: europe-west1
          GOOGLE_CLOUD_PROJECT: itpc-gcp-cp-pe-eng-claude
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          npm install -g @mariozechner/pi-coding-agent
          pi install npm:pi-provider-vertex-anthropic
          
          echo "Running pi command with prompt: ${{ github.event.comment.body }}"
          pi --print \
            --no-skills \
            --no-prompt-templates \
            --skill ./skills/migrate-spring-to-quarkus \
            --session-dir ./pi-session \
            --provider vertex-anthropic \
            --model claude-opus-4-6 \
            ${{ github.event.comment.body }}
          
          echo "pi command executed."

      - name: Export and Zip Session
        if: always()
        run: |
          SESSION_DIR=./pi-session
          echo "Session dir: $SESSION_DIR"
          
          LATEST_JSONL_FILE=$(ls -t "${SESSION_DIR}"*.jsonl | head -n 1)
          FULL_FILENAME=$(basename "$LATEST_JSONL_FILE")
          BASENAME_ONLY=${FULL_FILENAME%.*}
          
          echo "Session jsonl name: $FULL_FILENAME"
          echo "Session id: $BASENAME_ONLY"
          
          pi --export "$LATEST_JSONL_FILE" "pi-session-$BASENAME_ONLY.html" -p
          zip -r "pi-session-$BASENAME_ONLY.zip" pi-session-$BASENAME_ONLY.html

      - name: Upload Session Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pi-jonl-session
          path: pi-session-*.zip
          retention-days: 2